### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ShallMate** [ghoshbishakh/pci#4]
ECDSA/P256Element.cpp:64:47: error: 'int EC_POINT_get_affine_coordinates_GFp(const EC_GROUP, const EC_POINT, BIGNUM*, BIGNUM*, BN_CTX*)' is deprecated: Since OpenSSL 3.0**

Hello, Professor. I have the following problem when compiling. But I don't seem to have installed openssl, why is this error reported? Shouldn't it be reported that openssl cannot be found? Or should I just install openssl below version 3.0?

**Comment by ghoshbishakh** [comment]
`EC_POINT_get_affine_coordinates_GFp(` is unfortunately now private concept, meaning it not intended to be used from outside openssl library. I would suggest you to use < 3.0.

But it seems you have set the warnings to be treated as errors while compiling. Turning that off might let you use this with version 3 also.

**Comment by rbkhmrcr** [comment]
To be concrete, removing `-Werror` from CONFIG allows compilation to succeed even with openssl version 3.0+
